export const APPEARANCE_ATTRIBUTE_DEFAULTS = {
    bg_accent: '#15B8A9',
    font: '"Ubuntu", sans-serif',
    border_radius: '8px',
    shadow: '0px 0px 16px 0px #3f3f4629',
    button_border_radius: '8px',
    bg_button_primary: '#15B8A9',
    color_button_primary: '#ffffff',
    bg_button_primary_hover: '#1A5B57',
    color_button_primary_hover: '#ffffff',
    bg_button_inactive: '#edeff3',
    color_button_inactive: '#ffffff',
    bg_button_selected: '#15B8A9',
    color_button_selected: '#ffffff',
    bg_button_selected_hover: '#1A5B57',
    color_button_selected_hover: '#ffffff',
    bg_button_selected_selected: '#ffffff',
    color_button_selected_selected: '#22292f',
    bg_button_secondary: '#edeff2',
    color_button_secondary: '#ffffff',
    bg_button_secondary_hover: '#1A5B57',
    color_button_secondary_hover: '#ffffff',
    bg_sidebar: '#f9fafb',
    color_sidebar: '#22292F',
    color_border_selected: '#15B8A9',
}
